all: exe lib


exe:cs251.ex1
lib:cs251.a

CC=gcc
CFLAGS= -g -I. -DDBG
MAKELIB=ar
RANLIB=ranlib
TH=-pthread -lm
mainobj=prog.o
SOURCES = $(wildcard *.c)

OBJS = $(patsubst %.c, %.o, $(SOURCES))
LIBOBJS = $(filter-out $(mainobj),$(OBJS))

cs251.ex1:$(OBJS)
	$(CC) $(CFLAGS) -o $@ $^

$(OBJS) : common.h

cs251.a:$(LIBOBJS)
	$(MAKELIB) rc $@ $(LIBOBJS)
	$(RANLIB) $(TH) $@

clean:
	rm -f *.o cs251.ex1 cs251.a
	
